create table if not exists department
(
    id   bigint generated by default as identity,
    name varchar(255),
    constraint department_pkey
        primary key (id)
);

create table if not exists employee
(
    id        bigint generated by default as identity,
    birthdate date         not null,
    full_name varchar(255) not null,
    constraint employee_pkey
        primary key (id)
);

create table if not exists employee_of_the_month
(
    id             bigint generated by default as identity,
    selected_month varchar(255),
    selection_time timestamp,
    employee_id    bigint,
    constraint employee_of_the_month_pkey
        primary key (id),
    constraint fkph22w8uleul817mow211h8mk2
        foreign key (employee_id) references employee
);

create table if not exists office
(
    id       bigint generated by default as identity,
    location varchar(255),
    name     varchar(255),
    constraint office_pkey
        primary key (id)
);

create table if not exists employment_detail
(
    id            bigint generated by default as identity,
    end_date      date,
    process_time  timestamp,
    start_date    date   not null,
    department_id bigint not null,
    employee_id   bigint not null,
    office_id     bigint not null,
    constraint employment_detail_pkey
        primary key (id),
    constraint fkqd39dk18exafohb26wp0ubuhb
        foreign key (department_id) references department,
    constraint fkc8mc7a1ujglnlqpwj1dv7ds77
        foreign key (employee_id) references employee,
    constraint fksxtd0qkqafb9q7367x98a6shg
        foreign key (office_id) references office
);

create table if not exists payroll
(
    id           bigint generated by default as identity,
    payment_date date   not null,
    salary       double precision,
    employee_id  bigint not null,
    constraint payroll_pkey
        primary key (id),
    constraint fk5o7fr6cbvrkgud2unv0p5rqlm
        foreign key (employee_id) references employee
);

